### ISSUE TITLE
/usr/bin/python3: No module named pip

### ISSUE THREAD

**Issue by barryboom** [donaldzou/wireguard-dashboard#10]
trying to run dependancies as advised and getting /usr/bin/python3: No module named pip
i even rebuild server to 18.04 so its a fresh install but still the same 

is there a specfic setup needed on insatlling Python 3.7?

**Comment by donaldzou** [comment]
Hi, I think you did not install `pip`. You can use the following command to install on Ubuntu

`sudo apt install python3-pip`

**Comment by barryboom** [comment]
> 
> 
> Hi, I think you did not install `pip`. You can use the following command to install on Ubuntu
> 
> `sudo apt install python3-pip`

thanks for quick reply and this did indeed resolve the above error wonder if its worth having that command as part of the steps to help newbies like me

**Comment by donaldzou** [comment]
This would be a good idea actually :)
