### ISSUE TITLE
Any plans for Authentication requirement

### ISSUE THREAD

**Issue by barryboom** [donaldzou/wireguard-dashboard#12]
Hi dashboard seems to work well enough and certainly something i have been looking for and glad to say it does seem to work for me anyway on Ubunutu 20.04 and 20.10 been testing on various VM in DCs in the US , NL and UK 

One thing however that i would like to see is some form of authentication seen as the service allows creation and deletion of peers

**Comment by donaldzou** [comment]
Yes, this would be implement into the future version

**Comment by donaldzou** [comment]
This feature is finished developing and is doing final testing.

**Comment by barryboom** [comment]
Excellent looking forward to having some security on the dash and can then
leave it active without potential snooping
