### ISSUE TITLE
QR Code.

### ISSUE THREAD

**Issue by Trackhe** [donaldzou/wireguard-dashboard#15]
Show an QR Code. For the Client.

**Comment by bluecraank** [comment]
This would be a huuuuuuge improvement, because i didnt saw any wireguard dashboard or OS like opnsense which does have such a QR Code for the Config. Please add it!

**Comment by donaldzou** [comment]
> This would be a huuuuuuge improvement, because i didnt saw any wireguard dashboard or OS like opnsense which does have such a QR Code for the Config. Please add it!

Yes I'm thinking to put that in the next release, but the thing is, we need to store each peer's private key into the dashboard too to be able to generate the QR code, which is something i don't feel safe to do. But I'm thinking a way to implement that.

**Comment by donaldzou** [comment]
This feature has been added to the next release. Thanks everyone who brought this idea!

**Comment by bluecraank** [comment]
Thanks!

**Comment by bluecraank** [comment]
I'll try your beta release out!
