### ISSUE TITLE
Able to see initial dashboard and wg0 as active however unable to see clients or any additional info. May be similar to issue#3

### ISSUE THREAD

**Issue by robchez** [donaldzou/wireguard-dashboard#21]
**Describe The Problem**
Have same/similar issue as described in [Issue# 3](https://github.com/donaldzou/wireguard-dashboard/issues/3). Able to get the dashboard running however only displays Wg0. When selecting that interface shows blank screen. Did run `sh wgd.sh update` to make sure had the latest version

**Expected Error / Traceback**
```
[08/May/2021 10:44:14] "GET /get_config/wg0 HTTP/1.1" 500 -
[2021-05-08 10:44:31,342] ERROR in app: Exception on /get_config/wg0 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dashboard.py", line 406, in get_conf
    "peer_data": get_peers(config_name),
  File "dashboard.py", line 183, in get_peers
    get_conf_peers_data(config_name)
  File "dashboard.py", line 142, in get_conf_peers_data
    total_sent = cur_i[0]['total_sent']
IndexError: list index out of range


```
**To Reproduce**
Default page shows Wg0.  When  selecting Wg0 returns blank page with navigation on left still visible.  Error shown above. 

**OS Information:**

```
 PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
 
- Python Version: Python 3.7.3-1

```

**Sample of your `.conf` file**
```
username = admin
password = ABCD

[Server]
wg_conf_path = /etc/wireguard/
app_ip = 0.0.0.0
app_port = 10086
auth_req = false
version = v2.0
```
**My WG Directory Structure**
Not sure if this might be the problem. I did move a few client configs to root /etc/wireguard and I did see them in the dashboard but no metrics. 
```
/etc/wireguard
├── client
└── keys
    ├── client
    │   ├── private
    │   └── public
    └── server
        ├── private
        └── public
```

**Comment by donaldzou** [comment]
Hi, could you provide a sample of your client configuration file please?

**Comment by robchez** [comment]
Sure here is one of my configs. 

````
[Interface]
Address = 10.0.0.4/32
DNS = 192.168.86.1 
PrivateKey = abc1234

[Peer]
PublicKey = abc1235
Endpoint = myendpoint.enpoint.123:51820
AllowedIPs = 0.0.0.0/0
PersistentkeepAlive = 60
````

**Comment by donaldzou** [comment]
Hi, I'm thinking that you could point the dashboard to where you have the configuration saved, and make sure it have **read** permission for your current user.

**Comment by robchez** [comment]
Right, I have wg0.config in /etc/wireguard/ and the rest of the configs a few subdirs down.  Is the dashboard looking for them to all be in the same directory (wg will read subdirs and does work. I have the subdirs because I have a lot of configs.)?  If so that's likely my problem.

**Comment by donaldzou** [comment]
I see, the dashboard will only look for `.conf` in the top-level directory.
