### ISSUE TITLE
Add YunoHost support

### ISSUE THREAD

**Issue by Stylix58** [donaldzou/wireguard-dashboard#23]
**Is your feature request related to a problem? Please describe.**
I think some people want to see an easy way (with an GUI) to install it.

**Describe the solution you'd like**
Add support for YunoHost (make an separed repo for the app).
I can do it if anyboy wants! (I have already packaged some apps).

**Comment by donaldzou** [comment]
Hi! Thank you for this suggestion, this would be a great idea and I would love to integrate wg-dashboard into YunoHost! Please tell me if I need to make any changes or updates to be working perfectly with YunoHost.

**Comment by tituspijean** [comment]
Hello! I do not see any particular step for you to make, @donaldzou. 😉 Thank *you* for this project!

I have created a branch of YunoHost's WireGuard app with WireGuard Dashboard as its UI (https://github.com/YunoHost-Apps/wireguard_ynh/tree/wireguard-dashboard). It seems to be working so far, so it may surely become its own YunoHost app soon.

Maybe some general remarks that may be better suited in their own issues:
- The commands require `root` access (that's understandable). Ideally using `/etc/sudoers.d` to restrict which commands the app can run would slightly improve safety (but I am by no means an expert). (cf. issue 8)
- Upon fresh install, without at least an Interfance and one Peer manually configured, the webapp bugs out. Creating interfaces and peers directly from the webapp, combined with the QR code support (issue 15) from another issue, would be a great addition.

**Comment by donaldzou** [comment]
@tituspijean Hi thank you for replying and pointing out some bugs and suggestions! I will do some bug fix in my next version release :)

**Comment by donaldzou** [comment]
Bug fixed on the newest release ;)
