### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mcohen20** [donaldzou/wireguard-dashboard#25]
I get Internal Server Error after logging in the first time. I went into debug mode and I am Getting Permission denied on /etc/wireguard. Is there any additional permissions that need to be setup?

**Comment by donaldzou** [comment]
Hi, please make sure the user running the dashboard have execution and read permission of `/etc/wireguard`, you can try to this command `sudo chmod -R 755 /etc/wireguard`

**Comment by mcohen20** [comment]
That was it!
