### ISSUE TITLE
load balancing ?

### ISSUE THREAD

**Issue by GPConnect** [donaldzou/wireguard-dashboard#26]
**Is your feature request related to a problem? Please describe.**
wireguard is a client and server at the same time that can connect an infinite number of host to create a mesh networking ! if i got more than one wireguard should i install the dashboard on each of them ? or could it be a better way ?

**Describe the solution you'd like**
can we have one dashboard to visualize several wireguard host ?

**Comment by donaldzou** [comment]
As for now, I think you can only install on each of them, since the dashboard need to access each configuration file locally and access each wireguard by `wg show` or `wg-quick`.
