### ISSUE TITLE
PersistentKeepalive

### ISSUE THREAD

**Issue by Nas-au** [donaldzou/wireguard-dashboard#28]
**Describe The Problem**
When adding PersistentKeepalive manually  it get removed after restarting the wg0 
**Expected Error / Traceback**
```
Please provide the error traceback here
```

**To Reproduce**
Please provide how you run the dashboard

**OS Information:**
 - OS: [e.g. Ubuntu 18.02]
 - Python Version: [e.g v3.7]

```

**Comment by donaldzou** [comment]
Hi, to be able to edit the `.conf` manually, you need to make sure you `wg-quick down <config_name>` before editing it, otherwise when you try to `wg-quick down`, wireguard will rewrite the `.conf` of what it loaded before (i.e then conf before you edit).
