### ISSUE TITLE
Auto start on reboot option 

### ISSUE THREAD

**Issue by barryboom** [donaldzou/wireguard-dashboard#29]
**Is your feature request related to a problem? Please describe.**
Running dashboard on Ubuntu 21.04 on a test server and seems to work perfectly fine other than adding peers although i use a different WG setup so may related to that.

One thing i have however noticed on all builds is having to log back in via putty and start the service after any server reboots which can be annoying at times.

**Describe the solution you'd like**
option within settings to set or add set dashboard to load on boot or instructions how to add a script / job to do this if desired.

**Comment by donaldzou** [comment]
This is a great idea, i will add this into the next version

**Comment by a1ekseev** [comment]
I think this issue can be resolved with systemd.

**Comment by donaldzou** [comment]
This issue resolved in the next released ;)

**Comment by barryboom** [comment]
Sorry on late response have followed the guide to startup on a reboot although downloaded file and edited and reuploaded as dont like the VIM editors in putty.
Good news is though it worked for me running ubuntu 21.10 which is my test server next steps will be to get dashboard loaded on to my PROD servers on 20.04.3 which i did have original dashboard on but loving the latest builds and always seems to be getting better so keep up the great work.
