### ISSUE TITLE
Server will not accept password

### ISSUE THREAD

**Issue by ben-dd** [donaldzou/wireguard-dashboard#33]
No matter what I do, I cant get the server to accept my password.

I tried to use the default settings of `admin` /  `admin` (SHA256). 

I edited the `wg-dashboard.ini` file and changed both the username and password, stop and start the server, and it still wont accept. 

Any ideas?

**Comment by donaldzou** [comment]
> No matter what I do, I cant get the server to accept my password.
> 
> 
> 
> I tried to use the default settings of `admin` /  `admin` (SHA256). 
> 
> 
> 
> I edited the `wg-dashboard.ini` file and changed both the username and password, stop and start the server, and it still wont accept. 
> 
> 
> 
> Any ideas?

Hi, can you tell me what did you edit the  the ini file? Because the password originally stored in the ini file "admin" hashed in SHA256. Please make sure that you change the password using the dashboard settings instead of changing the file directly.

**Comment by ben-dd** [comment]
I originally tried to use the default login username and password. I hashed `admin` using a converter but it wouldnt accept it. Thats when I went in and tried changing the ini file with different values for both but still couldnt get it to work.

**Comment by donaldzou** [comment]
Could you post the ini file plz?

**Comment by ben-dd** [comment]
```
[Account]
username = admin
password = myPassword

[Server]
wg_conf_path = /etc/wireguard
app_ip = serverIP
app_port = 10086
auth_req = true
version = v2.1
dashboard_refresh_interval = 15000
```

**Comment by donaldzou** [comment]
> ```
> [Account]
> username = admin
> password = myPassword
> 
> [Server]
> wg_conf_path = /etc/wireguard
> app_ip = serverIP
> app_port = 10086
> auth_req = true
> version = v2.1
> dashboard_refresh_interval = 15000
> ```

Hi, I'm not sure why is different after you hashed the password with other hash tool. But to make sure it work perfectly, you can delete the `.ini` file and restart the dashboard, login with `admin` as your username and password, and then change it in the **setting** page in the dashboard :) Please comment if you still encounter the problem ;)

**Comment by ben-dd** [comment]
1. `./wgd.sh stop`
2. `rm -rf wg-dashboard.ini`
3. `./wgd.sh start`
4. Copy password directly from the `wg-dashboard.ini`
5. Results in attached video:

https://user-images.githubusercontent.com/40916720/127924321-600de5b2-4d23-4808-aaca-1750fcdac2a7.mov

**Comment by donaldzou** [comment]
Ahhh I see, the default username and password is just `admin` and `admin`, the password that stored in the `ini` file is `admin` hashed in `SHA256`. Every time when you login, the dashboard will hash and check if it is the same as the one stored in the `ini` file. So try `admin` and username and `admin` as password ;)

**Comment by ben-dd** [comment]
Oof. My bad. Thank you for the help!

**Comment by donaldzou** [comment]
No problem! Glad to help ;)

**Comment by adrinux** [comment]
I was trying to set a new password during deploy via Ansible. I generated a new password with ```mkpasswd --method=sha-256``` and it's added to wg-dashboard.ini correctly but doesn't work.

I suspect because mkpasswd adds a salt to the hash.

Can you share details of how you generate a compatible hash @donaldzou ?

**Comment by donaldzou** [comment]
Hi @adrinux , in the dashboard, it uses the python's hash library with SHA256 and encode into UTF-8 `[src/dashboard.py?plain=L708](password = hashlib.sha256(data['password'].encode()))`

**Comment by donaldzou** [comment]
Hi @adrinux, I'm not so sure how `mkpasswd` works, I will look into that. For the dashboard, it uses python's `hashlib` with `SHA256` without salt, so you can see here: https://github.com/donaldzou/WGDashboard/blob/cd84674ae028f57d0799e5971619d7bb7fba27e0/src/dashboard.py?plain=L708#L708

**Comment by adrinux** [comment]
Thanks. It seems mkpasswd won't hash _without_ a salt, so I found this one liner to use instead:
```
echo -n mypassword | sha256sum | awk '{print $1}'
```
Had Ansible write the results of that into wg-dashboard.ini, works perfectly.

**Comment by donaldzou** [comment]
> Thanks. It seems mkpasswd won't hash _without_ a salt, so I found this one liner to use instead:
> 
> ```
> 
> echo -n mypassword | sha256sum | awk '{print $1}'
> 
> ```
> 
> Had Ansible write the results of that into wg-dashboard.ini, works perfectly.

That's great!! I'm thinking would you mind to share your script to configure WGDashboard on Ansible? I think people would love to have this resource ;)
