### ISSUE TITLE
Allowed IPs, Endpoint, DNS Server Configuration via dashboard

### ISSUE THREAD

**Issue by bluecraank** [donaldzou/wireguard-dashboard#38]
**Is your feature request related to a problem? Please describe.**
Needed to define dns server, endpoint and allowedips

**Describe the solution you'd like**
On the dashboard, a wg0 configuration panel with endpoint ip, dns and allowedips

**Comment by donaldzou** [comment]
This has been added to the next release. You can check it out in the v2.2-beta branch. It might be still not stable, I will be keep testing in the next few days.
