### ISSUE TITLE
Multi User Login / Register

### ISSUE THREAD

**Issue by bluecraank** [donaldzou/wireguard-dashboard#42]
**Is your feature request related to a problem? Please describe.**
A nice improvement would be a multi user function, so the admin can create accounts for other people, who needs to sign in into the dashboard

**Describe the solution you'd like**
user page for creating editing and deleting users

**Comment by donaldzou** [comment]
Hi, since i want to keep the dashboard to simple and easy to use, this function will not be consider at this time.

**Comment by bluecraank** [comment]
Okay!
