### ISSUE TITLE
DNS and AllowedIP as Global Config

### ISSUE THREAD

**Issue by bluecraank** [donaldzou/wireguard-dashboard#44]
**Is your feature request related to a problem? Please describe.**
Currently, you need to type everytime again the dns servers for every peer
Also, AllowedIPs ist 0.0.0.0/0 default which is not good if u just want specific ips

**Comment by donaldzou** [comment]
Hi, yes this function has been added already.

**Comment by bluecraank** [comment]
Where can i find it? I only find 0.0.0.0/0 in conf_get.html but not in the Dashboard

**Comment by donaldzou** [comment]
I haven't commit the newest one yet. There's still some bug need to be fix
