### ISSUE TITLE
Bug: Domain endpoint is being replaced with IP.

### ISSUE THREAD

**Issue by tandy-1000** [donaldzou/wireguard-dashboard#48]
My config looks like this:
```
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
ListenPort = 
PrivateKey = 

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 10.0.0.2/32
Endpoint = DOMAIN:37469
```

After running wireguard dashboard, it becomes this:
```
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
ListenPort = 
PrivateKey = 

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 10.0.0.2/32
Endpoint = IP:37469
```

**Comment by tandy-1000** [comment]
This doesn't seem to be a wireguard-dashboard issue, but a wireguard issue when using the `SaveConfig=true` option, I am not sure how to stop this though, and I can't use wireguard-dashboard unless there is a way to work around this.

**Comment by donaldzou** [comment]
Hi, the `SaveConfig` is for WireGuard-Tool to be able add peers or remove peers without turning it off, edit it and turn it back on. If you don't need to manage peers, you just want to monitor, you can set it to `false` ;)

**Comment by donaldzou** [comment]
After some digging, WireGuard itself will replace the domain into an IP address after it resolved from DNS. Seems like it is a feature/bug from WireGuard itself. I'll keep looking into solution and hope that you can give my dashboard a try in the future ;)

**Comment by tandy-1000** [comment]
Thank you, yes it seems this is the expected action.

I would like to use wireguard-dashboard, but the one thing that I am unsure about is hosting a web service as root, it seems insecure. Is there any way around doing this?
