### ISSUE TITLE
Domain:10086 is not working .

### ISSUE THREAD

**Issue by a181129471** [donaldzou/wireguard-dashboard#49]
Hi ,
Domain:10086 is not working . connection refused , is it dashboard issue ? or my server setting issue?

**Comment by a181129471** [comment]
NVM,I have it settled .

**Comment by donaldzou** [comment]
Hi, could you tell me how you fixed it? Is it because of firewall?

**Comment by a181129471** [comment]
> Hi, could you tell me how you fixed it? Is it because of firewall?

that was resolved by redirecting traffic from 10086 to port 80
