### ISSUE TITLE
Peer Endpoint Allowed IPs under Settings only allow /0 /8 /16 /24 /32 but not e.g /13

### ISSUE THREAD

**Issue by bluecraank** [donaldzou/wireguard-dashboard#50]
**Describe The Problem**
I want to route only private networks like 172.16.0.0/13 but the dashboard do not allow that

**Expected Error / Traceback**
```
Peer Endpoint Allowed IPs Format Incorrect. Example: 192.168.1.1/32 or 192.168.1.1/32,192.168.1.2/32
```

**Solution**
Allow every suffix

**Comment by donaldzou** [comment]
I will add all other prefix in the next bug fix.
