### ISSUE TITLE
Failed Logins Give Incorrect Error Message

### ISSUE THREAD

**Issue by ricohard** [donaldzou/wireguard-dashboard#52]
An incorrect login will return a message indicting that the login should have worked.

Login with something obviously wrong: Dave / Dave for example and the message returned will be:

"Username or Password is correct."

<img width="564" alt="Screenshot 2021-08-16 at 21 54 08" src="https://user-images.githubusercontent.com/11992416/129628262-3cbca50b-9ef9-4876-8b2c-16bd93ab448d.png">

I'm thinking that this should fix it:

```
473c473
<         session['message'] = "Username or Password is correct."
---
>         session['message'] = "Username or Password is not correct."
```

**Comment by donaldzou** [comment]
😅 oops! I never noticed this problem. I'll fix it in the next release. Thank you!
