### ISSUE TITLE
Tools Don't Work on Settings Page

### ISSUE THREAD

**Issue by ricohard** [donaldzou/wireguard-dashboard#54]
**Describe The Problem**
When in the Home page or the Configurations (wg0) page the Ping and Traceroute tools are available and appear to work. When in the Settings page they do not. There is no popup interface and nothing is logged to say why there is no response.

**Expected Error / Traceback**
None available.

**To Reproduce**
Go to the Settings page then select Ping or Traceroute on from the options on the left. Neither will respond.

**OS Information:**
```
root@wireguard:~/wireguard-dashboard/src# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@wireguard:~/wireguard-dashboard/src#

root@wireguard:~/wireguard-dashboard/src# uname -a
Linux wireguard 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
root@wireguard:~/wireguard-dashboard/src#

root@wireguard:~/wireguard-dashboard/src# python3 --version
Python 3.7.3
root@wireguard:~/wireguard-dashboard/src#
```

**Sample of your `.conf` file**
I don't think this is needed but it's already on issue #53

**Comment by donaldzou** [comment]
This will be fix in the next release ;)
