### ISSUE TITLE
Ping Returns Incorrect Fail Count

### ISSUE THREAD

**Issue by ricohard** [donaldzou/wireguard-dashboard#56]
**Describe The Problem**
Pinging a client that is offline shows a mismatch between pings sent, pings received and pings lost.

**Expected Error / Traceback**
N/A

**To Reproduce**
Ping a currently offline client.

**OS Information:**
```
pi@wireguard:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@wireguard:~ $

pi@wireguard:~ $ uname -a
Linux wireguard 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
pi@wireguard:~ $

pi@wireguard:~ $ python3 --version
Python 3.7.3
pi@wireguard:~ $
```

**Sample of your `.conf` file**
N/A
<img width="787" alt="Screenshot 2021-08-17 at 10 02 05" src="https://user-images.githubusercontent.com/11992416/129698860-2547f37b-b01d-4d3a-b311-1ef7951ef62d.png">

**Comment by donaldzou** [comment]
Hi, in the dependency's documentation, package loss equal 1 means all package loss. I'll make an adjustment to this.
