### ISSUE TITLE
Server Public Key Case Wrong

### ISSUE THREAD

**Issue by ricohard** [donaldzou/wireguard-dashboard#57]
**Describe The Problem**
All the peer keys under wg0 are shown with the correct case but the server public key at the top of the page (and the Home page) is shown all in capitals. The copy works with the correct case though.

**Expected Error / Traceback**
N/A

**To Reproduce**
Go to the Home page or the configurations page and look at the server key.

**OS Information:**
```
pi@wireguard:~/wgkeys $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@wireguard:~/wgkeys $

pi@wireguard:~/wgkeys $ uname -a
Linux wireguard 5.10.17-v7+ #1421 SMP Thu May 27 13:59:01 BST 2021 armv7l GNU/Linux
pi@wireguard:~/wgkeys $

pi@wireguard:~/wgkeys $ python3 --version
Python 3.7.3
pi@wireguard:~/wgkeys $
```

**Sample of your `.conf` file**
N/A

This might be a deliberate design decision but it just seems out of keeping with the way the rest of the keys are displayed.

**Comment by donaldzou** [comment]
I just made the adjustment on the CSS ;)
