### ISSUE TITLE
Configurable Persistent keepalive Settings

### ISSUE THREAD

**Issue by reafian** [donaldzou/wireguard-dashboard#62]
**Is your feature request related to a problem? Please describe.**
Some of my clients use Persistent keepalive to maintain a connection and they have different values depending on their likely uses. Being able to set this on the UI would be a good thing.

**Describe the solution you'd like**
Under each client have an option to set Persistent keepalive.

**Comment by bluecraank** [comment]
Agree!

**Comment by ricohard** [comment]
I've got to say sorry for spamming you with bugs and requests but this is a pretty damn neat interface and I'm totally on-board with what you're doing here. :-)

**Comment by donaldzou** [comment]
> I've got to say sorry for spamming you with bugs and requests but this is a pretty damn neat interface and I'm totally on-board with what you're doing here. :-)

Hahaha no worries!! I'm open to all sorts of suggestions and bug reports!
