### ISSUE TITLE
configparser.NoSectionError: No section: 'Interface'

### ISSUE THREAD

**Issue by ramalmaty** [donaldzou/wireguard-dashboard#66]
Hi Thank you for such a good project of wireguard-dashboard,

 While i try to run the web interface, I am getting the following error. can you please help me with this.

I installed it on ubuntu 20.04

Think it got something to do with the Flask, Login page is opening, and when trying to login, it is throwing as internal error on web, in logs, found the reason below:

Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 1146, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Interface'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/etc/wireguard-dashboard/dashboard.py", line 677, in index
    return render_template('index.html', conf=get_conf_list())
  File "/usr/local/etc/wireguard-dashboard/dashboard.py", line 308, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "/usr/local/etc/wireguard-dashboard/dashboard.py", line 264, in get_conf_pub_key
    pri = conf.get("Interface", "PrivateKey")
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None

**Comment by donaldzou** [comment]
Hi, could you provide a sample of your configuration file please?

**Comment by ramalmaty** [comment]
[Interface]                                                                                                          Address = 192.168.xx.1/24                                                                                            ListenPort = xxxx                                                                                                   PrivateKey = xxxxxxxxx                                                            PostUp = iptables -I INPUT 1 -i wg0 -j ACCEPT; iptables -I FORWARD 1 -i eth0 -o wg0 -j ACCEPT; iptables -I FORWARD 1 -i wg0 -o eth0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 192.168.xx.0/24 -o eth0 -j MASQUERADE                    
PostDown = iptables -D INPUT -i wg0 -j ACCEPT ; iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT ; iptables -D FORWARD -i wg0 -o eth0 -j ACCEPT ; iptables -t nat -D POSTROUTING -s 192.168.xx.0/24 -o eth0 -j MASQUERADE                     

[Peer]                                                                                                               PublicKey = xxxxxxx                                                             AllowedIPs = 192.168.xx.2/32                                                                                         [Peer]                                                                                                               PublicKey = xxxxxxxx                                                             AllowedIPs = 192.168.xx.3/32                                                                                         [Peer]                                                                                                               PublicKey = xxxxxxx
AllowedIPs = 192.168.xx.4/32

**Comment by donaldzou** [comment]
Hi, do you have any non-WireGuard configuration under the folder?

**Comment by ramalmaty** [comment]
~                                                                                                                    ~                                                                                                                    ~                                                                                                                    ~                                                                                                                    [Account]                                                                                                            username = admin                                                                                                     password = 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918                                          [Server]                                                                                                             wg_conf_path = /etc/wireguard                                                                                        app_ip = 0.0.0.0                                                                                                     app_port = 10086                                                                                                     auth_req = false                                                                                                     version = v2.2.1                                                                                                     dashboard_refresh_interval = 15000                                                                                   dashboard_sort = status                                                                                              [Peers]                                                                                                              peer_global_dns = 1.1.1.1                                                                                            peer_endpoint_allowed_ip = 0.0.0.0/0                                                                                 
          
File in wireguard-dashboard folder:                                                                                    "wg-dashboard.ini"

**Comment by donaldzou** [comment]
Sorry, I mean under `/etc/wireguard`

**Comment by ramalmaty** [comment]
Oh, its nothing in there except wg0.conf

**Comment by donaldzou** [comment]
Hi, sorry for the late reply. Could you check the permission of reading the configuration file?

**Comment by ramalmaty** [comment]
Sorry for the delay, was busy, Please find the below permissions

drwxr--r--   2 root root 4096 Aug 23 22:02 .
drwxr-xr-x 100 root root 4096 Aug 27 06:51 ..
-rwxr--r--   1 root root  824 Aug 21 18:17 wg0.conf

**Comment by omargohan** [comment]
I had the same issue, but I fixed it changing the permissions as follow.

```bash
$ sudo chmod 755 /etc/wireguard/
$ sudo chmod 664 /etc/wireguard/*.conf
```

I hope this helps.

**Comment by donaldzou** [comment]
Hi, thank you for replying. Do you mind remove all files under `wireguard-dashboard/db` ? and then run the dashboard with the following command: `sudo ./wgd.sh debug` ?

**Comment by FrmCaaS** [comment]
Hi
I have the same problem with dashboard version 2.2.1
**Log**
frmadmin@srv1:~/wireguard-dashboard/src$ **rm db/hi.txt** 
frmadmin@srv1:~/wireguard-dashboard/src$ 
frmadmin@srv1:~/wireguard-dashboard/src$ ./wgd.sh debug
Starting Wireguard Dashboard in the foreground. 
 * Serving Flask app 'Wireguard Dashboard' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.1.11:10086/ (Press CTRL+C to quit)
User not loggedin - Attemped access: index
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET / HTTP/1.1" 302 -
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /signin HTTP/1.1" 200 -
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/js/bootstrap.bundle.js HTTP/1.1" 200 -
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/js/tools.js HTTP/1.1" 200 -
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/css/dashboard.css HTTP/1.1" 200 -
192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/logo.png HTTP/1.1" 404 -
192.168.1.26 - - [31/Aug/2021 16:48:13] "POST /auth HTTP/1.1" 302 -
[2021-08-31 16:48:13,932] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "dashboard.py", line 677, in index
    return render_template('index.html', conf=get_conf_list())
  File "dashboard.py", line 308, in get_conf_list
    temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
  File "dashboard.py", line 264, in get_conf_pub_key
    pri = conf.get("Interface", "PrivateKey")
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
**configparser.NoSectionError: No section: 'Interface'**
192.168.1.26 - - [31/Aug/2021 16:48:13] "GET / HTTP/1.1" 500 -
192.168.1.26 - - [31/Aug/2021 16:48:13] "GET /favicon.ico HTTP/1.1" 404 -


**Content of my /etc/wireguard**

frmadmin@srv1:~/wireguard-dashboard/src$ sudo ls -l /etc/wireguard/
total 8
drwxr--r-- 2 root root 4096 Aug 31 16:20 myKeys
-rwxr--r-- 1 root root  428 Aug 31 16:15 wg0.conf

**Configuration file**
[Interface]
PrivateKey = *********************************
ListenPort = 8443
SaveConfig = false
Address = 192.168.31.1/24
postup = sudo iptables -F FORWARD
postup = sudo iptables -F INPUT
postup = sudo iptables -A INPUT -s 192.168.31.0/24 -j ACCEPT
postup = sudo iptables -A FORWARD -s 192.168.31.0/24 -o ens18 -j ACCEPT

[Peer]
PublicKey = ***************************
AllowedIPS = 192.168.31.2/32

Thanks in advance for your help

Regards

**Comment by donaldzou** [comment]
> Hi
> I have the same problem with dashboard version 2.2.1
> **Log**
> frmadmin@srv1:~/wireguard-dashboard/src$ **rm db/hi.txt** frmadmin@srv1:~/wireguard-dashboard/src$
> frmadmin@srv1:~/wireguard-dashboard/src$ ./wgd.sh debug
> Starting Wireguard Dashboard in the foreground.
> 
> * Serving Flask app 'Wireguard Dashboard' (lazy loading)
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: off
> * Running on all addresses.
>   WARNING: This is a development server. Do not use it in a production deployment.
> * Running on http://192.168.1.11:10086/ (Press CTRL+C to quit)
>   User not loggedin - Attemped access: index
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET / HTTP/1.1" 302 -
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /signin HTTP/1.1" 200 -
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/js/bootstrap.bundle.js HTTP/1.1" 200 -
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/js/tools.js HTTP/1.1" 200 -
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/css/dashboard.css HTTP/1.1" 200 -
>   192.168.1.26 - - [31/Aug/2021 16:48:12] "GET /static/logo.png HTTP/1.1" 404 -
>   192.168.1.26 - - [31/Aug/2021 16:48:13] "POST /auth HTTP/1.1" 302 -
>   [2021-08-31 16:48:13,932] ERROR in app: Exception on / [GET]
>   Traceback (most recent call last):
>   File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
>   response = self.full_dispatch_request()
>   File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
>   rv = self.handle_user_exception(e)
>   File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
>   rv = self.dispatch_request()
>   File "/home/frmadmin/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
>   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "dashboard.py", line 677, in index
>   return render_template('index.html', conf=get_conf_list())
>   File "dashboard.py", line 308, in get_conf_list
>   temp = {"conf": i, "status": get_conf_status(i), "public_key": get_conf_pub_key(i)}
>   File "dashboard.py", line 264, in get_conf_pub_key
>   pri = conf.get("Interface", "PrivateKey")
>   File "/usr/lib/python3.8/configparser.py", line 781, in get
>   d = self._unify_values(section, vars)
>   File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
>   raise NoSectionError(section) from None
>   **configparser.NoSectionError: No section: 'Interface'**
>   192.168.1.26 - - [31/Aug/2021 16:48:13] "GET / HTTP/1.1" 500 -
>   192.168.1.26 - - [31/Aug/2021 16:48:13] "GET /favicon.ico HTTP/1.1" 404 -
> 
> **Content of my /etc/wireguard**
> 
> frmadmin@srv1:~/wireguard-dashboard/src$ sudo ls -l /etc/wireguard/
> total 8
> drwxr--r-- 2 root root 4096 Aug 31 16:20 myKeys
> -rwxr--r-- 1 root root 428 Aug 31 16:15 wg0.conf
> 
> **Configuration file**
> [Interface]
> PrivateKey = *********************************
> ListenPort = 8443
> SaveConfig = false
> Address = 192.168.31.1/24
> postup = sudo iptables -F FORWARD
> postup = sudo iptables -F INPUT
> postup = sudo iptables -A INPUT -s 192.168.31.0/24 -j ACCEPT
> postup = sudo iptables -A FORWARD -s 192.168.31.0/24 -o ens18 -j ACCEPT
> 
> [Peer]
> PublicKey = ***************************
> AllowedIPS = 192.168.31.2/32
> 
> Thanks in advance for your help
> 
> Regards

Hi, do you mind move the file `mykey` out of `/etc/wireguard`, and remove all files under `wireguard-dashboard/db` and restart the dashboard? Thanks!

**Comment by FrmCaaS** [comment]
Hi donaldzou
Thanks for your answer

I moved the folder and remove file under db
frmadmin@srv1:~/wireguard-dashboard/src$ **sudo ls -l /etc/wireguard/**
total 4
-rwxr--r-- 1 root root 428 Aug 31 16:15 wg0.conf

frmadmin@srv1:~/wireguard-dashboard/src$ **ls db/**
frmadmin@srv1:~/wireguard-dashboard/src$ 


But the problem is still the same

**Comment by donaldzou** [comment]
Hi @FrmCaaS , thank you for the quick response, can you make sure that the `/etc/wireguard` have read and execute permission? Can you try `chmod 755 /etc/wireguard`? This will give read and execute permission to all user group. But if this still doesn't fix the problem, you can revoke the permission settings.

**Comment by donaldzou** [comment]
> Sorry for the delay, was busy, Please find the below permissions
> 
> drwxr--r-- 2 root root 4096 Aug 23 22:02 .
> drwxr-xr-x 100 root root 4096 Aug 27 06:51 ..
> -rwxr--r-- 1 root root 824 Aug 21 18:17 wg0.conf

Hi, can you also try setting the permission with the following command: `chmod 755 /etc/wireguard`?

**Comment by FrmCaaS** [comment]
Good news..
It works with permission set to 755

frmadmin@srv1:~/wireguard-dashboard/src$ sudo ls -l /etc/wireguard/
total 4
-rwxr--r-- 1 root root 428 Aug 31 16:15 wg0.conf

frmadmin@srv1:~/wireguard-dashboard/src$ sudo ls -l /etc/ | grep wireguard
drwxr-xr-x 2 root root       4096 Aug 31 16:54 wireguard


I guess the problem was the permission of the wireguard folder more than the access to the configuration file.
Do you agree with that ?
Thanks for your help

Franck

**Comment by FrmCaaS** [comment]
Donald
In addition I made a test putting some comments in my wg0.conf file and move myKeys in /etc/wireguard.
And it still works fine
If this can help.

Thanks again

**Comment by donaldzou** [comment]
> Good news..
> 
> It works with permission set to 755
> 
> 
> 
> frmadmin@srv1:~/wireguard-dashboard/src$ sudo ls -l /etc/wireguard/
> 
> total 4
> 
> -rwxr--r-- 1 root root 428 Aug 31 16:15 wg0.conf
> 
> 
> 
> frmadmin@srv1:~/wireguard-dashboard/src$ sudo ls -l /etc/ | grep wireguard
> 
> drwxr-xr-x 2 root root       4096 Aug 31 16:54 wireguard
> 
> 
> 
> 
> 
> I guess the problem was the permission of the wireguard folder more than the access to the configuration file.
> 
> Do you agree with that ?
> 
> Thanks for your help
> 
> 
> 
> Franck

Ehhh!!!! This is a great news🙌🙌 I'll update the documentation. Thank you so much!!

**Comment by FrmCaaS** [comment]
Yes great news. A very good first step ;)
Any idea about why the counters in the dashboard are always 0 when the wg command shows some traffic ?

![image](https://user-images.githubusercontent.com/89863424/131557109-2b10ebc3-caa9-45ec-9bd9-17d9e180c70a.png)

frmadmin@srv1:~/wireguard-dashboard/src$ **sudo wg**
interface: wg0
  public key: **********************
  private key: (hidden)
  listening port: 8443

peer: ************************
  endpoint: xx.yy.zz.aa:22576
  allowed ips: 192.168.31.2/32
  latest handshake: 53 minutes, 3 seconds ago
  **transfer: 93.20 KiB received, 267.19 KiB sent**
frmadmin@srv1:~/wireguard-dashboard/src$

**Comment by donaldzou** [comment]
> Yes great news. A very good first step ;)
> Any idea about why the counters in the dashboard are always 0 when the wg command shows some traffic ?
> 
> ![image](https://user-images.githubusercontent.com/89863424/131557109-2b10ebc3-caa9-45ec-9bd9-17d9e180c70a.png)
> 
> frmadmin@srv1:~/wireguard-dashboard/src$ **sudo wg**
> interface: wg0
> public key: **********************
> private key: (hidden)
> listening port: 8443
> 
> peer: ************************
> endpoint: xx.yy.zz.aa:22576
> allowed ips: 192.168.31.2/32
> latest handshake: 53 minutes, 3 seconds ago
> **transfer: 93.20 KiB received, 267.19 KiB sent**
> frmadmin@srv1:~/wireguard-dashboard/src$

Hi, that's because it won't fetch peer's data if the peer did not connect to wireguard. You can try connect your peer and it will show :)

**Comment by FrmCaaS** [comment]
Hi Donaldzou

sorry if I'm in a wrong section.
I tried to create another peer. it is connected but the counter remains at 0 in the dashboard

counters in the servers

peer: ****************
  endpoint: 89.95.201.249:41773
  allowed ips: 192.168.31.3/32
  latest handshake: 1 minute, 7 seconds ago
  **transfer: 153.79 KiB received, 1.93 MiB sent**

Counters in the peer
peer: ************************
  endpoint: 176.168.222.171:8443
  allowed ips: 192.168.1.0/24, 192.168.31.0/24
  latest handshake: 1 minute, 4 seconds ago
  **transfer: 1.92 MiB received, 152.35 KiB sent**

frmadmin@srv1:~$ cat wireguard-dashboard/src/db/wg0.json 
{"_default": {"1": {"id": "****************************** ", "private_key": "", "DNS": "1.1.1.1", "endpoint_allowed_ip": "0.0.0.0/0", "name": "", "total_receive": 0, "total_sent": 0, "total_data": 0, "endpoint": 0, "status": 0, "latest_handshake": 0, "allowed_ip": "192.168.31.2/32", "traffic": []}, "2": {"id": "********************************", "private_key": "", "DNS": "1.1.1.1", "endpoint_allowed_ip": "0.0.0.0/0", "name": "", **"total_receive": 0, "total_sent": 0, "total_data": 0, "endpoint": 0**, "status": 0, "latest_handshake": 0, "allowed_ip": "192.168.31.3/32", "traffic": []}}}frmadmin@srv1:~$ 



any idea?

Thank you

**Comment by donaldzou** [comment]
Did you tried to connect the peer while the dashboard is running?
