### ISSUE TITLE
Better distribution as a python package (PIP/PyPI)

### ISSUE THREAD

**Issue by jan-di** [donaldzou/wireguard-dashboard#72]
**Is your feature request related to a problem? Please describe.**
The current deployment via git works, but is not ideally as one has to manually switch to a specific version and load dependencies to update the dashboard.

**Describe the solution you'd like**
I would like to see the dashboard packaged as a python package that is installable via pip from the python package index (PyPI). That would make updating much easier and streamlined with other python based applications.

Edit:
There is a nice description on how to public a package automatically via GitHub actions at the python documention:
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by donaldzou** [comment]
Hi, this is a great idea! I will look into it!
